config/routes.rb
Rails.application.routes.draw do
  root 'faces#index'

  post 'recognize' => 'faces#recognize'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController
  def index
    @faces = ['Ninguno']
  end

  def recognize
    uploaded_io = params[:pic]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    client = Face.get_client(api_key: ENV['API_KEY'], api_secret: ENV['API_SECRET'])
    @faces = client.faces_detect(file: File.new('public/uploads/' + uploaded_io.original_filename, 'rb'))['photos'][0]['tags'].map { |tag| tag['uids'][0]['uid'] if tag['uids'] }
    # @faces = client.faces_detect(urls:  ['http://www.handsonbanking.org/financial-education/wp-content/uploads/2013/05/hero.jpg', 'http://cdn.business2community.com/wp-content/uploads/2016/02/progressive-profiling-lead-scoring-better-leads.jpg.jpg'])
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faces_helper.rb
module FacesHelper
  def self.images
    [
      'https://skybiometry.com/wp-content/uploads/2015/09/eva-2ppl-web-1-e1451908961635.jpg',
      'https://skybiometry.com/wp-content/uploads/2016/01/recognition-2nd-e1451908699204.jpg',
      'https://skybiometry.com/wp-content/uploads/2015/09/face-recognition-negative-1-e1451909042742.jpg',
      'https://skybiometry.com/wp-content/uploads/2015/09/eva-3ppl-web-1-e1451909054787.jpg'
    ]
  end
end

app/views/faces/index.html.erb
<h1>Face detection</h1>
<%= form_tag recognize_path, multipart: true do %>
  <%= file_field_tag 'pic', id: 'newImage' %>
  <%= submit_tag 'ENVIAR' %>
<% end %>
<div class="">
  Rostros encontrados
  <ul>
    <% @faces.each do |face| %>
      <li><%= face %></li>
    <% end %>
  </ul>
  <img id="preview" src="#" alt="your image" />
</div>
<script>
  $('#preview').hide();
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#preview').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#newImage").change(function(){
    $('#preview').show();
    readURL(this);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceRecognition</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>